### ISSUE TITLE
How to access app?

### ISSUE THREAD

**Issue by aks-** [jasisk/sliderule#1]
Hey, how do I access the app once it's running?

**Comment by jasisk** [comment]
The only real route in the app is `/presentation/:pid` [as defined in the routes file](https://github.com/jasisk/universal-react-redux-react-router-example/blob/c4e4e05bfcd5f99ab88321099ade5862e7922e1e/common/routes/app.js#L4). The valid `:pid` values are taken from the config ([as defined in the server routes](https://github.com/jasisk/universal-react-redux-react-router-example/blob/c4e4e05bfcd5f99ab88321099ade5862e7922e1e/server/routes/index.js#L13-L24)) which you can find in [`server/config/config.json`](https://github.com/jasisk/universal-react-redux-react-router-example/blob/c4e4e05bfcd5f99ab88321099ade5862e7922e1e/server/config/config.json#L18-L22).

So, that's a long winded way of saying to go to:
http://localhost:8000/presentations/universality-0 or 
http://localhost:8000/presentations/universality-0/connections

:grinning:

**Comment by aks-** [comment]
Awesome, thanks it works for me now :)
